{% set name = "humanfilt" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation .
  entry_points:
    - humanfilt = humanfilt.cli:main

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - bwa
    - bowtie2
    - minimap2
    - samtools
    - kraken2
    - trim-galore
    - fastqc
    - bbmap            # bbduk.sh, dedupe.sh
    - fastuniq
    - seqkit
    - curl
    - zstd
    - coreutils
    - tar
    - pigz

test:
  commands:
    - humanfilt --help

about:
  home: https://github.com/your-org/humanfilt
  license: MIT
  summary: "WGS/RNA-seq decontamination with first-run Zenodo downloads."

