package:
    name: humanfilt
    version: 0.1.1

source:
    url: https://github.com/jprehn-lab/humanfilt/archive/refs/tags/v0.1.1.tar.gz
    sha256: f2e0768e10399d0fe91e337fc1326d8ff2c7b7a2918d69084beddfbe614b035d

build:
    noarch: python
    number: 0
    entry_points:
      - humanfilt=humanfilt.cli:main

requirements:
    host:
      - python >=3.10
      - pip
      - setuptools
  run:
      - python >=3.10
      - bwa
      - samtools
      - minimap2
      - bowtie2
      - kraken2
      - trim-galore
      - bbmap     # bbduk.sh, dedupe.sh
      - fastuniq
      - seqkit
      - pigz

test:
    commands:
      - humanfilt --help
    imports:
      - humanfilt

about:
    home: https://github.com/jprehn-lab/humanfilt
    license: MIT
    summary: WGS human read filtering with auto-downloaded references (GRCh38/T2T/HPRC/UniVec + Kraken2).

extra:
    recipe-maintainers:
      - marsfro   

