package:
    name: humanfilt
    version: 1.0.0

source:
    path: ..

build:
    noarch: python
    number: 0
    entry_points:
      - humanfilt=humanfilt.cli:main

requirements:
    host:
      - python >=3.10
      - pip
      - setuptools
  run:
      - python >=3.10
      - bwa
      - samtools
      - minimap2
      - bowtie2
      - kraken2
      - trim-galore
      - bbmap     # bbduk.sh, dedupe.sh
      - fastuniq
      - seqkit
      - pigz

test:
    commands:
      - humanfilt --help
    imports:
      - humanfilt

about:
    home: https://github.com/jprehn-lab/humanfilt
    license: MIT
    summary: WGS human read filtering (GRCh38/T2T/HPRC/UniVec + Kraken2).

extra:
    recipe-maintainers:
      - marsfro   
