package:
  name: humanfilt
  version: 0.1.0

source:
  url: https://github.com/your-org/humanfilt/archive/refs/tags/v0.1.0.tar.gz
  sha256: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef  # TODO: replace with real sha256 for v0.1.0

build:
  noarch: python
  number: 0
  entry_points:
    - humanfilt=humanfilt.cli:main

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - bwa
    - samtools
    - minimap2
    - bowtie2
    - kraken2
    - trim-galore
    - bbmap     # bbduk.sh, dedupe.sh
    - fastuniq
    - seqkit
    - pigz

test:
  commands:
    - humanfilt --help
    - humanfilt run --mode wgs --input . --output . --report _noop.csv --threads 1 --no-auto-setup || true

about:
  home: https://github.com/your-org/humanfilt
  license: MIT
  summary: WGS human read filtering with auto-downloaded references (GRCh38/T2T/HPRC/UniVec + Kraken2).

extra:
  recipe-maintainers:
    - your_bioconda_handle
